# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	clear_derived_data
    increment_build_number(xcodeproj: "RecordGram.xcodeproj")
    build_app(workspace: "RecordGram.xcworkspace", scheme: "RecordGram")
    upload_to_testflight

    download_dsyms
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files

    commit = last_git_commit
    commit_version_bump(message: commit[:message])
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    notification(subtitle: "Finished Uploading", message: "Successfully deployed new RG Update.")
  end
end
